#spring.application.name=school-im-system
#
## ===================== ??????? =====================
## MySQL????MySQL 8.x????com.mysql.cj.jdbc.Driver?
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
## ????????????????????
#spring.datasource.username=root
## ??????????????????
#spring.datasource.password=123456
## ?????URL
## ???xm-blog???????????????????GMT%2b8???GMT+8?????
#spring.datasource.url=jdbc:mysql://localhost:3306/zzu_project?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=GMT%2b8&allowPublicKeyRetrieval=true
#
## ===================== ?????? =====================
## ???????????100MB?
#spring.servlet.multipart.max-file-size=100MB
## ???????????100MB??????max-file-size?
#spring.servlet.multipart.max-request-size=100MB
#


spring.application.name=school-im-system

# ===================== ????? =====================
# MySQL???MySQL 8.x ?????
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# ??????????????????root???????
spring.datasource.username=gly
# ????1?????????? gly123
spring.datasource.password=
# ????2?IP??10.66.6.221?????33065?????3?useSSL=false ?? useSSL=true???SSL?
spring.datasource.url=jdbc:mysql://10.66.6.221:33065/XYWAQSJCZ?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=true&serverTimezone=GMT%2b8&allowPublicKeyRetrieval=true

# ===================== ?????? =====================
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB


# ??yaml??
#chat:
#upload:
#dir: /data/app/uploads/chat
#access-url-prefix: https://your-domain.com/images/

chat.upload.dir= /data/app/
chat.upload.access-url-prefix= http://your-domain.com/images/
